name: Qneuro
description: Windows Ble plugin.
publish_to: "none"
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  win_ble:
    path: ../
  cupertino_icons: ^1.0.2
  msix: ^3.16.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
